apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    service: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongodb
  template:
    metadata:
      labels:
        service: mongodb
    spec:
      volumes:
      - name: opa-config-vol
        configMap:
          name: opa-istio-config
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      containers:
      - name: opa
        image: openpolicyagent/opa:latest-envoy
        volumeMounts:
        - readOnly: true
          mountPath: /config
          name: opa-config-vol
        args:
        - "run"
        - "--server"
        - "--ignore=.*"
        - "--config-file=/config/conf.yaml"
        - "--authorization=basic"
        - "--addr=http://127.0.0.1:8181"
        - "--diagnostic-addr=0.0.0.0:8282"
      - name: mongodb
        image: {{ .Values.image.repo }}/rs-mongodb:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always
